[{
	"resource": "/C:/Users/risro/Projects/VSCode-GitHub/residential-wiring-simulator/src/components/BreakerPanel.tsx",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "',' expected.",
	"source": "ts",
	"startLineNumber": 780,
	"startColumn": 1,
	"endLineNumber": 780,
	"endColumn": 3,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/risro/Projects/VSCode-GitHub/residential-wiring-simulator/src/components/BreakerPanel.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'as'.",
	"source": "ts",
	"startLineNumber": 780,
	"startColumn": 1,
	"endLineNumber": 780,
	"endColumn": 3,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/risro/Projects/VSCode-GitHub/residential-wiring-simulator/src/components/BreakerPanel.tsx",
	"owner": "typescript",
	"code": "2554",
	"severity": 8,
	"message": "Expected 1 arguments, but got 3.",
	"source": "ts",
	"startLineNumber": 780,
	"startColumn": 1,
	"endLineNumber": 780,
	"endColumn": 16,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/risro/Projects/VSCode-GitHub/residential-wiring-simulator/src/components/BreakerPanel.tsx",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "',' expected.",
	"source": "ts",
	"startLineNumber": 780,
	"startColumn": 4,
	"endLineNumber": 780,
	"endColumn": 16,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/risro/Projects/VSCode-GitHub/residential-wiring-simulator/src/components/BreakerPanel.tsx",
	"owner": "typescript",
	"code": "2693",
	"severity": 8,
	"message": "'BreakerPoles' only refers to a type, but is being used as a value here.",
	"source": "ts",
	"startLineNumber": 780,
	"startColumn": 4,
	"endLineNumber": 780,
	"endColumn": 16,
	"modelVersionId": 2,
	"origin": "extHost1"
}]