[{
	"resource": "/c:/Users/risro/Projects/VSCode-GitHub/residential-wiring-simulator/src/components/BreakerPanelLayout.tsx",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "',' expected.",
	"source": "ts",
	"startLineNumber": 1841,
	"startColumn": 21,
	"endLineNumber": 1841,
	"endColumn": 23,
	"modelVersionId": 7,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/risro/Projects/VSCode-GitHub/residential-wiring-simulator/src/components/BreakerPanelLayout.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'as'.",
	"source": "ts",
	"startLineNumber": 1841,
	"startColumn": 21,
	"endLineNumber": 1841,
	"endColumn": 23,
	"modelVersionId": 7,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/risro/Projects/VSCode-GitHub/residential-wiring-simulator/src/components/BreakerPanelLayout.tsx",
	"owner": "typescript",
	"code": "2554",
	"severity": 8,
	"message": "Expected 1 arguments, but got 3.",
	"source": "ts",
	"startLineNumber": 1841,
	"startColumn": 21,
	"endLineNumber": 1841,
	"endColumn": 35,
	"modelVersionId": 7,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/risro/Projects/VSCode-GitHub/residential-wiring-simulator/src/components/BreakerPanelLayout.tsx",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "',' expected.",
	"source": "ts",
	"startLineNumber": 1841,
	"startColumn": 24,
	"endLineNumber": 1841,
	"endColumn": 35,
	"modelVersionId": 7,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/risro/Projects/VSCode-GitHub/residential-wiring-simulator/src/components/BreakerPanelLayout.tsx",
	"owner": "typescript",
	"code": "2693",
	"severity": 8,
	"message": "'BreakerType' only refers to a type, but is being used as a value here.",
	"source": "ts",
	"startLineNumber": 1841,
	"startColumn": 24,
	"endLineNumber": 1841,
	"endColumn": 35,
	"modelVersionId": 7,
	"origin": "extHost1"
}]